import Head from "next/head"
import styles from "../styles/Home.module.css"
import Header from "../components/Header"
import LotteryEntrance from "../components/LotteryEntrance"
import { useMoralis } from "react-moralis"

const supportedChains = ["31337", "11155111"]

export default function Home() {
    const { isWeb3Enabled, chainId } = useMoralis()
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next Aoo</title>
                <meta name="description" content="Generated by created next app"></meta>
                <link rel="icon" href="/favicon.ico"></link>
            </Head>
            <Header></Header>
            {isWeb3Enabled ? (
                <div className="flex flex-row">
                    <LotteryEntrance className="p-8"></LotteryEntrance>
                </div>
            ) : (
                <div>Please connect to a Wallet</div>
            )}
        </div>
    )
}
